export const FETCH_UPDATE_DATA = 'FETCH_UPDATE_DATA';
export const FETCH_UPDATE_DATA_SUCCESS = 'FETCH_UPDATE_DATA_SUCCESS';
export const FETCH_UPDATE_DATA_FAILURE = 'FETCH_UPDATE_DATA_FAILURE';

export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS';