export const FETCH_VIEW = 'FETCH_VIEW';
export const FETCH_VIEW_SUCCESS = 'FETCH_VIEW_SUCCESS';

export const UPDATE_VIEW_COUNT = 'UPDATE_VIEW_COUNT';
export const UPDATE_VIEW_COUNT_SUCCESS = 'UPDATE_VIEW_COUNT_SUCCESS';
//export const FETCH_VIEW_FAILURE;